### ISSUE TITLE
Hydration energies benchmark

### ISSUE THREAD

**Issue by martimunicoy** [martimunicoy/offpele-benchmarks#10]
# Description
This benchmark evaluates the implicit solvent implementation by predicting the hydration free energy on a database of compounds with reported experimental data ([FreeSolv](https://github.com/MobleyLab/FreeSolv)).

# Remarks
## offpele version
Please, note that several changes have been introduced to `offpele` in order to have good performance in this benchmark as much as possible. Thus, we should use, at least, version 0.3.0 or newer.

## Requirements
When using OPLS parameters we need access to Schrodinger's `ffld_server`. For this reason, PELE needs to know the path to Schrodinger's installation folder. This path must be set with an environment variable before calling offpele. Otherwise, offpele will complain when trying to execute the `ffld_server`. The environment variable that is required is:

```
export SCHRODINGER='/path/to/Schrodinger/installation/schrodinger2020-2
```

## How to manage parameters
Now, we can assign parameters from two different sources. By default, the main source is the `Open Force Field Toolkit`. However, we can use `OPLS2005`' nonbonding parameters with the command below:

```
python offpele/main.py input_ligand.pdb --use_OPLS_nonbonding_params
```

or

```
molecule = Molecule('input_ligand.pdb')
molecule.parameterize('openff_unconstrained-1.2.0.offxml', use_OPLS_nonbonding_params=True)
```

The `OPLS2005` parameters can be also assigned to bonds and angles. In this case, we need the following command:

```
python offpele/main.py input_ligand.pdb --use_OPLS_nonbonding_params --use_OPLS_bonds_and_angles
```

or

```
molecule = Molecule('input_ligand.pdb')
molecule.parameterize('openff_unconstrained-1.2.0.offxml', use_OPLS_nonbonding_params=True, use_OPLS_bonds_and_angles=True)
```

Finally, different charge methods can also be defined with the following commands:

```
python offpele/main.py input_ligand.pdb --charges_method 'charges_method_name'
```

or

```
molecule = Molecule('input_ligand.pdb')
molecule.parameterize('openff_unconstrained-1.2.0.offxml', charges_method='charges_method_name')
```

The list of available charges methods (`charges_method_name`) is:
- `gasteiger`
- `am1bcc`
- `OPLS`

# Benchmark
The following scenarios should be benchmarked:

- [x] Standard PELE with `OPLS2005` parameters and the `VDGBNP` implicit solvent (use `PlopRotTemp` in this case)
- [x] Standard PELE with `OPLS2005` parameters and the `OBC` implicit solvent (use `PlopRotTemp` in this case.
- [x] PELE with `OFF` parameters, the `OBC` implicit solvent and `gasteiger` charges.
- [x] PELE with `OFF` parameters, the `OBC` implicit solvent and `am1bcc` charges.
- [x] PELE with `OFF` parameters, the `OBC` implicit solvent and `OPLS` charges.
- [x] PELE with `OFF` bonding parameters, the `OPLS2005` non-bonding parameters, `VDGBNP` implicit solvent and `OPLS` charges.
- [x] PELE with `OFF` dihedral parameters, the `OPLS2005` non-bonding, bond and angle parameters, `VDGBNP` implicit solvent and `OPLS` charges.
- [x] PELE with `OFF` bonding parameters, the `OPLS2005` non-bonding parameters, `VDGBNP` implicit solvent and `am1bcc` charges.
- [x] PELE with `OFF` dihedral parameters, the `OPLS2005` non-bonding, bond and angle parameters, `VDGBNP` implicit solvent and `am1bcc` charges.

Maybe other protocols can also be interesting. 

# Extra
- [x] Develop methods to automatically plot the regressions and histograms of this benchmark

**Comment by laumalo** [comment]
To benchmark all the mentioned scenarios, the following bash file, [benchmark.sh](https://github.com/martimunicoy/offpele-benchmarks/blob/solvent/benchmarks/solvent/benchmark.sh), has been implemented: 

`.\benchmark.sh `

Each scenario can be benchmarked individually by the following command, for instance:  

`python main.py OFFOPLS -solvent VDGBNP -c am1bcc -nb -ba  -p -o OFFOPLS_out9`

where the flag `-p` indicates that the corresponding plots (histogram of the absolute difference and regression Experimental value vs. Energetic difference) will be created inside the output folder. 

And, `OFFOPLS` is the method used.  
Three methods can be distinguish: 

- `OPLS` where the input parameter that should be given via flags is the implicid solvent `-solvent` .
- `OFF` where the input parameters that should be given via flags are the  implicid solvent `-solvent` and the charges method `-c`.
- `OFFOPLS` where the input parameters that should be given via flags are the implicid solvent `-solvent` and the charges method `-c` and if the bonding, non-bonding and angle parameters should be obteined by `OPLS2005` the following flags have to be called `-nd` and `-ba`. 

The results of the scenarios benchmarked can be found under the following folders: 

-  Standard PELE with OPLS2005 parameters and the VDGBNP implicit solvent (use PlopRotTemp in this case) -> `OPLS_out4`
-  Standard PELE with OPLS2005 parameters and the OBC implicit solvent (use PlopRotTemp in this case. -> `OPLS_out5`
-  PELE with OFF parameters, the OBC implicit solvent and gasteiger charges.  -> `OFF_out1`
-  PELE with OFF parameters, the OBC implicit solvent and am1bcc charges. -> `OFF_out2`
-  PELE with OFF parameters, the OBC implicit solvent and OPLS charges. -> `OFF_out3`
-  PELE with OFF bonding parameters, the OPLS2005 non-bonding parameters, VDGBNP implicit solvent and OPLS charges. -> `OFFOPLS_out6`
-  PELE with OFF dihedral parameters, the OPLS2005 non-bonding, bond and angle parameters, VDGBNP implicit solvent and OPLS charges. -> `OFFOPLS_out7`
-  PELE with OFF bonding parameters, the OPLS2005 non-bonding parameters, VDGBNP implicit solvent and am1bcc charges. -> `OFFOPLS_out8`
-  PELE with OFF dihedral parameters, the OPLS2005 non-bonding, bond and angle parameters, VDGBNP implicit solvent and am1bcc charges. -> `OFFOPLS_out9`

**Comment by laumalo** [comment]
### Results from the regressions and histograms of this benchmark

- PELE with OFF parameters, the OBC implicit solvent and gasteiger charges. -> `OFF_out1`

<img src="https://user-images.githubusercontent.com/44496034/93330172-ac33ba80-f81e-11ea-97ec-e881b795c54b.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93330176-ae961480-f81e-11ea-8b23-fc96be6380db.png" width="400"/>

- PELE with OFF parameters, the OBC implicit solvent and am1bcc charges. -> `OFF_out2`

<img src="https://user-images.githubusercontent.com/44496034/93331525-b22a9b00-f820-11ea-84c6-7e5e41c19b79.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93331528-b48cf500-f820-11ea-9651-653c961b7539.png" width="400"/>

- PELE with OFF parameters, the OBC implicit solvent and OPLS charges. -> `OFF_out3`

<img src="https://user-images.githubusercontent.com/44496034/93331591-d1c1c380-f820-11ea-8cac-64855cce4609.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93331593-d38b8700-f820-11ea-8978-0b89955af0b6.png" width="400"/>

- Standard PELE with OPLS2005 parameters and the VDGBNP implicit solvent (use PlopRotTemp in this case) -> `OPLS_out4`

<img src="https://user-images.githubusercontent.com/44496034/93335662-18b2b780-f827-11ea-8d8f-a60713ce55a2.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93335665-1a7c7b00-f827-11ea-93ba-130f9c8fa1ae.png" width="400"/>

- PELE with OFF bonding parameters, the OPLS2005 non-bonding parameters, VDGBNP implicit solvent and OPLS charges. -> `OFFOPLS_out6`

<img src="https://user-images.githubusercontent.com/44496034/93331850-37ae4b00-f821-11ea-83e3-7e12a5d91112.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93331859-38df7800-f821-11ea-83e5-f1fb4acc60a8.png" width="400"/>

- PELE with OFF dihedral parameters, the OPLS2005 non-bonding, bond and angle parameters, VDGBNP implicit solvent and OPLS charges. -> `OFFOPLS_out7`

<img src="https://user-images.githubusercontent.com/44496034/93331912-4bf24800-f821-11ea-9896-0bb61ed56e5a.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93331917-4f85cf00-f821-11ea-92fc-80b62b5cc9a9.png" width="400"/>

- PELE with OFF bonding parameters, the OPLS2005 non-bonding parameters, VDGBNP implicit solvent and am1bcc charges. -> `OFFOPLS_out8`

<img src="https://user-images.githubusercontent.com/44496034/93331992-6e846100-f821-11ea-9978-4ec6aae62284.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93331994-704e2480-f821-11ea-9b89-572d42734565.png" width="400"/>

- PELE with OFF dihedral parameters, the OPLS2005 non-bonding, bond and angle parameters, VDGBNP implicit solvent and am1bcc charges. -> `OFFOPLS_out9`

<img src="https://user-images.githubusercontent.com/44496034/93332051-83f98b00-f821-11ea-9faa-bf21ca8bdddb.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93332058-85c34e80-f821-11ea-810a-e69d5a5a14d7.png" width="400"/>

**Comment by laumalo** [comment]
## Results from the regressions and histograms of this benchmark (after fixing the bug in OBC implementation)

### OFF benchmarks
- PELE with OFF parameters, the OBC implicit solvent and gasteiger charges. -> `OFF_out1`

<img src="https://user-images.githubusercontent.com/44496034/93484143-dca05500-f901-11ea-8e99-c3ae8714a47b.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93484150-df02af00-f901-11ea-802f-690a66e6f00d.png" width="400"/>

- PELE with OFF parameters, the OBC implicit solvent and am1bcc charges. -> `OFF_out2`

<img src="https://user-images.githubusercontent.com/44496034/93496494-918d3e80-f90f-11ea-8a80-c477f2781b1a.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93496498-93570200-f90f-11ea-9706-47a927eca759.png" width="400"/>

- PELE with OFF parameters, the OBC implicit solvent and OPLS charges. -> `OFF_out3`

<img src="https://user-images.githubusercontent.com/44496034/93493506-432a7080-f90c-11ea-9cff-a89d04696b85.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93493509-445b9d80-f90c-11ea-9fdc-0de59dfb2d6e.png" width="400"/>

## OPLS benchmarks

- Standard PELE with OPLS2005 parameters and the VDGBNP implicit solvent (use PlopRotTemp in this case) -> `OPLS_out4`

<img src="https://user-images.githubusercontent.com/44496034/93486815-e8d9e180-f904-11ea-9363-e32d96353966.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93486824-eaa3a500-f904-11ea-8fd4-fc023308e12c.png" width="400"/>

- Standard PELE with OPLS2005 parameters and the OBC implicit solvent (use PlopRotTemp in this case. -> `OPLS_out5`

<img src="https://user-images.githubusercontent.com/44496034/93484489-402a8280-f902-11ea-84b3-cf87b1ff21f8.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93484493-41f44600-f902-11ea-9808-e5321722fbe4.png" width="400"/>

## OFF-OPLS benchmarks 

- PELE with OFF bonding parameters, the OPLS2005 non-bonding parameters, VDGBNP implicit solvent and OPLS charges. -> `OFFOPLS_out6`

<img src="https://user-images.githubusercontent.com/44496034/93517905-5ea57380-f92c-11ea-9dc5-957a0e9899a7.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93517910-606f3700-f92c-11ea-828e-86d6fbded477.png" width="400"/>

- PELE with OFF dihedral parameters, the OPLS2005 non-bonding, bond and angle parameters, VDGBNP implicit solvent and OPLS charges. -> `OFFOPLS_out7`

<img src="https://user-images.githubusercontent.com/44496034/93485066-f0988680-f902-11ea-925f-732bc8a5e679.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93485076-f2624a00-f902-11ea-954b-8e4cd9f9fa2b.png" width="400"/>



- PELE with OFF bonding parameters, the OPLS2005 non-bonding parameters, VDGBNP implicit solvent and am1bcc charges. -> `OFFOPLS_out8`

<img src="https://user-images.githubusercontent.com/44496034/93518075-a0361e80-f92c-11ea-9a97-2fa02b88cdfb.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93518077-a1674b80-f92c-11ea-9fef-78eaf46755a6.png" width="400"/>

- PELE with OFF dihedral parameters, the OPLS2005 non-bonding, bond and angle parameters, VDGBNP implicit solvent and am1bcc charges. -> `OFFOPLS_out9`

<img src="https://user-images.githubusercontent.com/44496034/93518202-ce1b6300-f92c-11ea-898a-d5b73d52db8f.png" width="400"/> <img src="https://user-images.githubusercontent.com/44496034/93518206-cf4c9000-f92c-11ea-8d2d-3673b488a733.png" width="400"/>
