### ISSUE TITLE
Function get_bonds does not keep whitespaces

### ISSUE THREAD

**Issue by martimunicoy** [martimunicoy/offpele-benchmarks#6]
Please, @laumalo, look at the function: [`get_bonds()`](https://github.com/martimunicoy/offpele-benchmarks/blob/66f1ee6305d82e722096bc8fb39a1a425ed5fc2d/benchmarks/rotamers/utils.py#L64) from `rotamers/utils.py`.  It needs to store also whitespaces to compare them afterwards. Currently, it ignores them and only saves the non-blank characters it finds in the rotamer library.

**Comment by martimunicoy** [comment]
Actually, I realized that the origin of the problem comes from replacing the '_' character by '' at line [71](https://github.com/martimunicoy/offpele-benchmarks/blob/66f1ee6305d82e722096bc8fb39a1a425ed5fc2d/benchmarks/rotamers/utils.py#L71):
```
rot = re.sub('_', '', rot)
```

**Comment by laumalo** [comment]
Yes, that was what I implemented to avoid  the inconsistency between the two files with having the _ before and after for the same bond. But removing this line it will take into account where are the spaces.
