### ISSUE TITLE
Improve functions to call PELE's minimization

### ISSUE THREAD

**Issue by martimunicoy** [martimunicoy/offpele-benchmarks#9]
There are several improvements and bug-fixes that we need to solve on the functions and classes that call PELE's minimization.

**Comment by martimunicoy** [comment]
Improvements list:
- [x] Replace bash commands by functions from Python libraries (such as `os.makedirs()` in [MoleculeMinimized.py](https://github.com/martimunicoy/offpele-benchmarks/blob/69722b5bdceb4c91287d6b56c423f82ba5760822/benchmarks/solvent/MoleculeMinimized.py#L37)) 
- [ ] Skip hardcoded paths to files such in [here](https://github.com/martimunicoy/offpele-benchmarks/blob/69722b5bdceb4c91287d6b56c423f82ba5760822/benchmarks/solvent/MoleculeMinimized.py#L73), use instead relative paths to local files found in the repository.
- [x] Use the `offpele`'s API to parameterize molecules, instead of the main.py such in [here](https://github.com/martimunicoy/offpele-benchmarks/blob/69722b5bdceb4c91287d6b56c423f82ba5760822/benchmarks/solvent/MoleculeMinimized.py#L48)
- [ ] Consider handling paths with pathlib's `Path` class

**Comment by martimunicoy** [comment]
Regarding the use of `offpele`'s API, below is an example of how to use it:
```
from offpele.topology import Molecule
from offpele.template import Impact
from offpele.solvent import OBC2

# Create representation of a particular molecule
molecule = Molecule(path_to_pdb_file)

# Generate its rotamer library
rotamer_library = offpele.topology.RotamerLibrary(molecule)
rotamer_library.to_file(rotamer_library_output_path)

# Generate its parameters and template file
molecule.parameterize(forcefield, charges_method=charges_method)
impact = Impact(molecule)
impact.write(impact_output_path)

# Generate its solvent parameters
solvent = OBC2(molecule)
solvent.to_json_file(solvent_output_path)
```

Besides, the DataLocal's output hierarchy can be constructed through the function [handle_output_paths()](https://github.com/martimunicoy/offpele/blob/bd9895eb73062315adb025fa5bd38bf48f1dde68/offpele/main.py#L73) from `main.py`

**Comment by laumalo** [comment]
The following PDB files: benzene.pdb and toluene.pdb present the following error when computing the PELE's minimization. 

`what():  /!\ Error in MacroBuilder::createMacro: /!\ Error in  ImpactTemplateReader::processRESXLine: Incorrect RESX line (wrong format) in file benz!!!!
`
And the same error for tolz.
